README.md, __tests__/main.test.ts, bin/build-test-release, lib/installer.js, src/installer.ts
With this PR it's possible to install nightly versions of Julia
I have not been able to figure out the workflow syntax equivalent to `allow_failures` on Travis, so I didn't add a proper example yet.
Example run: https://github.com/julia-actions/Example.jl/commit/4a5e78ea79ab25e5f69ccc4a257f07a44c9d447d/checks?check_suite_id=326520284
---
I wanted to add tests for `getDownloadURL` but I could not figure out how to mock the value of a global constant in jest. I'll tackle that another time.
---
This is the last feature that was still missing before the interface is stable/(mostly) complete. Once merged, I'll tag a `v1.0.0` release.
---
(fixes #5)
=> Support nightly Julia builds

.github/workflows/example-builds-nightly.yml, .github/workflows/example-builds.yml, README.md, lib/installer.js, src/installer.ts
=> Support release nightlies

.github/workflows/example-builds-nightly.yml, .github/workflows/example-builds.yml, README.md, lib/installer.js, lib/setup-julia.js, package-lock.json, package.json, src/installer.ts, src/setup-julia.ts
Still need to write tests so that we don't have to run absurd amounts of workflows to test this but the feature itself is ready for review.
=> Change show-versioninfo to always print full info for nightlies

lib/installer.js, package-lock.json, package.json, src/installer.ts
Closes #85
I don't have a proper JS/TS dev environment set up and I don't really want to dive into setting one up, so this is untested. Feel free to take over this branch :)
edit: ok turns out it's not super hard to run `npm install`. It seems to have doubled the size of `package-lock.json`, and I have absolutely no idea what that's about.
Here's the output of `npm install`:
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. …
```
=> Throw an informative error for non-existent version

README.md, lib/installer.js, package-lock.json, src/installer.ts
Setting the `arch` input to `aarch64` will install `aarch64` binaries,
intended to be used on aarch64-based self-hosted runners.
Please note that we currently don't run test builds on that
architecture, so we cannot guarantee that the input won't break
randomly, although there is no reason why it would.
In a future update, we may choose a default architecture based on the
arch of the runner.
Thanks to @giordano for providing a self-hosted runner for testing.
=> Add support for aarch64

action.yml, package-lock.json, package.json
EOL was almost a month ago. Woops.
I don't care about people using an old version of GitHub Enterprise, so I'm not going to annoy every single user of this action with a breaking update like GH did with their core actions. If you're a user of GHE: consider this a breaking update.
=> Update default runtime to node16

lib/installer.js, src/installer.ts
To allow for compatibility with the [`${{ runner.arch }}`](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context) variable, which takes on the following values: `X86`, `X64`, `ARM`, or `ARM64`.
Fixes #107
=> In the `arch` input, allow `ARM64` as a synonym for `aarch64`

lib/installer.js, src/installer.ts
To allow for compatibility with the [`${{ runner.arch }}`](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context) variable, which takes on the following values: `X86`, `X64`, `ARM`, or `ARM64`.
=> In the `arch` input, allow `X64` and `X86` as synonyms for `x64` and `x86`, respectively

.github/workflows/example-builds.yml, lib/installer.js, src/installer.ts
As seen in https://github.com/JuliaLang/VersionsJSONUtil.jl/pull/4#issuecomment-1198801820, we currently don't have macOS tarballs for 1.1, 1.2, 1.3.
So, in this PR, we first try to use the tarball, but we fall back to the `.dmg` if we can't find the tarball.
---
Depends on: https://github.com/JuliaLang/VersionsJSONUtil.jl/pull/4
See also: #105, https://github.com/JuliaLang/VersionsJSONUtil.jl/issues/3
=> On macOS, first try to find a tarball (`.tar.gz`) file, but fall back to `.dmg` if we can't find a tarball

README.md, __tests__/installer.test.ts, action.yml, lib/installer.js, lib/setup-julia.js, src/installer.ts, src/setup-julia.ts
=> Add the `include-all-prereleases` input

README.md
The workflow to build it is triggered manually as part of the release process now, so this should no longer be an issue and hasn't been one for quite a while.
=> Remove mention of auto-updating versions file

README.md
Things added/changed:
- Remove Dependabot badge in `README.md`.
- Looks like the Dependabot API is no longer accessible.
=> fix: remove Dependabot badge in `README.md`

lib/installer.js, src/installer.ts
If you give the version `1.9-nightly` this action hangs indefinitely.
```
##[debug]Downloading https://julialangnightlies-s3.julialang.org/bin/linux/x64/1.9/julia-latest-linux64.tar.gz
##[debug]Destination /home/pointcheck/actions-runner/_work/_temp/364c19a7-e87b-4032-96dd-6392988b11de
##[debug]Failed to download from "https://julialangnightlies-s3.julialang.org/bin/linux/x64/1.9/julia-latest-linux64.tar.gz". Code(404) Message(Not Found)
##[debug]Download of https://julialangnightlies-s3.julialang.org/bin/linux/x64/1.9/julia-latest-linux64.tar.gz failed, trying again. Error: Error: Unexpected HTTP response: 404
...
```
=> set retry limit

lib/installer.js, src/installer.ts
It currently takes almost a minute to install julia on windows via the .exe installer.
.zip takes ~42 seconds
.tar.gz takes ~12s :tada:
So let's use `.tar.gz` which is available all the way back to julia v1, and the exe if not
Closes https://github.com/julia-actions/setup-julia/issues/64
=> Use .tar.gz files where available for faster win install

package.json
Waiting for https://github.com/julia-actions/setup-julia/pull/171
=> Version 1.9.3

.github/scripts/common-tests.jl, .github/workflows/example-builds-defaultarch.yml, .github/workflows/example-builds-nightly-defaultarch.yml, .github/workflows/example-builds-nightly.yml, .github/workflows/example-builds.yml
This should fail on master, and will be added to #196 which should pass
The mtime test only runs on 1.7+ because that's when `pkgdir` is available, and the mtime issue isn't really a problem back then. It's more since stdlibs have started to be removed from the sysimage.
Interestingly on windows the archive mtimes are maintained, which explains why the cache action works well already on windows https://github.com/julia-actions/cache/issues/85#issue-2064424120
=> add test for julia install and mtime maintenance

README.md
Given the note in https://github.com/julia-actions/setup-julia#julia-versions the examples should have them
(I was just bitten by `version: 1.10` installing julia 1.1.1)
=> put quotes on readme version examples

.github/workflows/example-builds-nightly-defaultarch.yml, lib/installer.js, src/installer.ts
Testing with julia nightly on `macos-14` (aarch64) currently fails with:
```
Run julia-actions/setup-julia@v1
Download of https://julialangnightlies-s3.julialang.org/bin/mac/aarch64/julia-latest-mac64.tar.gz failed, trying again. Error: Error: Unexpected HTTP response: 404
```
The filename is slightly wrong and should have `macaarch64` instead of `mac64`, this PR tries to fix this for linux and macOS.
I also added `macOS-14` (for the [new M1 runners](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)) to the nightly tests.
Note that these URLs are a bit of a guesswork. On the official nightly downloads page they have a different format using a slightly more homogeneous pattern (at least for linux and macos):
- `x86_64`, …
=> Fix the Apple Silicon (macOS `aarch64` / `arm64`) URLs for Julia nightly

package-lock.json, package.json
Seems the semver package had a moderate fix that's good to get out
```
ian@Ians-MBP setup-julia % npm install
changed 6 packages, and audited 438 packages in 1s
32 packages are looking for funding
run `npm fund` for details
1 moderate severity vulnerability
To address all issues, run:
npm audit fix
Run `npm audit` for details.
ian@Ians-MBP setup-julia % npm audit fix
changed 4 packages, and audited 438 packages in 628ms
32 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
ian@Ians-MBP setup-julia % 
```
=> 1.9.6 and compat bump for node semver package

action.yml
Fixes #208 
Node 16 is deprecated, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> update to node20

package-lock.json, package.json
Follow-up to https://github.com/julia-actions/setup-julia/pull/209
=> Bump the version number to `2.0.0` in `package.json` and `package-lock.json`

.github/workflows/example-builds-nightly-defaultarch.yml
>  This is a scheduled macOS-11 brownout. The macOS-11 environment is deprecated and will be removed on June 28th, 2024.
=> CI: stop testing on macOS 11

lib/installer.js, src/installer.ts
Ref #240 
Ref #241
This PR does NOT fix the actual problem in #240 or #241, but it does fix the problem of `setup-julia` erroring silently and not printing a log message.
With this PR, as a general rule, we always print the error message before we throw the error.
=> Always print an error message, never error silently

lib/installer.js, src/installer.ts
Fixes #240 
Fixes #241 
At the end of the log message, we link to this Discourse post: https://discourse.julialang.org/t/how-to-fix-github-actions-ci-failures-with-julia-1-6-or-1-7-on-macos-latest-and-macos-14/117019
=> Improve the error logging for the case of Julia 1.6 or 1.7 on Apple Silicon (`macos-latest` or `macos-14`)

.github/workflows/example-builds.yml, README.md, action.yml, lib/setup-julia.js, src/setup-julia.ts
- I haven't found a way to catch https://github.com/julia-actions/setup-julia/issues/204 so explain the issue in the instructions 
- In preparation for 1.10 becoming LTS promote users to use "lts" rather than specify "1.6" explicitly.
i.e.
=> Improve example version instructions. Add info about "lts" if user specifies 1.6 explicitly
